# Generated by Django 3.0.5 on 2020-08-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogdata_modified_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
