# Generated by Django 3.0.5 on 2020-08-27 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_destination_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'verbose_name_plural': 'Products Package'},
        ),
        migrations.AlterModelOptions(
            name='destination_booking',
            options={'verbose_name_plural': 'Product Customer Booking'},
        ),
        migrations.AlterModelOptions(
            name='destination_category',
            options={'verbose_name_plural': 'Products Category'},
        ),
        migrations.AlterField(
            model_name='destination',
            name='price',
            field=models.IntegerField(help_text='Please Mention Currency', max_length=255),
        ),
    ]
